### ISSUE TITLE
[Bug Report] Write_root_pose_to_sim + write_data_to_sim does not move object in viewport

### ISSUE THREAD

**Issue by WenjingLi2036** [isaac-sim/IsaacLab#3851]
I defined a ball in the SceneCfg:
`self.ball:RigidObjectCfg = RigidObjectCfg(prim_path="{ENV_REGEX_NS}/Ball",`
                `spawn=sim_utils.SphereCfg(`
                `radius=0.037,`
                `rigid_props=sim_utils.RigidBodyPropertiesCfg(`
                    `kinematic_enabled=True,`
                    `disable_gravity=True,`
                `),`
`...`
`)`

During the RL training, the ball position is updated. I used the following code to update the ball position.
`pose = torch.zeros((self.num_envs, 7), device=self.device)`
`pose[:, :3] = self.ball`
`pose[:, 3] = 1.0`
`env_ids = torch.arange(self.num_envs, device=self.device)`
`self.pickleball_future_visual.write_root_pose_to_sim(pose, env_ids)`
`self.scene.write_data_to_sim()`
`...`
`self.sim.step()`
` self.scene.update(dt=self.physics_dt)`
`self.scene.render()`

The ball was visualized correctly when I use isaacsim 4.5.0 + isaaclab 2.1.0 but the ball was frozen at the environment origin when I use isaacsim 5.0 + the newest isaaclab.
It didn't affect the RL training results. So it should only be some rendering issues.          
        
I initially posted this issue to Isaacsim github repo (see https://github.com/isaac-sim/IsaacSim/issues/251). The team member thought the issue might be originated from isaaclab and suggested me posted here as well.

Any thoughts on this are highly appreciated!
        
        
      

### Isaac Sim version

5.0.0

### Operating System (OS)

Ubuntu 22.04

### GPU Name

RTX 5090

### GPU Driver and CUDA versions

Driver 570.172.08 CUDA 12.8

**Comment by RandomOakForest** [comment]
Thank you for posting this. We will investigate.

**Comment by PeterL-NV** [comment]
Hi @WenjingLi2036 ,
This is fixed in Isaac Sim 5.1.0, can you update your Isaac Sim and try again?

**Comment by Andrii0607** [comment]
@PeterL-NV 
I think the problem is still there.
When I run
./isaaclab.sh -p scripts/tools/record_demos.py --task Isaac-Stack-Cube-Franka-IK-Rel-v0 --device cpu --teleop_device keyboard --dataset_file ./datasets/dataset.hdf5 --num_demos 10
From this tutorial
https://isaac-sim.github.io/IsaacLab/main/source/overview/imitation-learning/teleop_imitation.html#collecting-demonstrations
The cubes are kind of offset from their origin. 

<img width="939" height="596" alt="Image" src="https://github.com/user-attachments/assets/9f11b971-6813-4596-a5ac-1c3336600522" />

If I move a cube a little bit, it jumps to the position where it supposed to be. 

<img width="939" height="596" alt="Image" src="https://github.com/user-attachments/assets/7c3f1b54-91e4-4f6b-a30a-d3b11bb5191c" />

I think this is a problem of the “write_root_pose_to_sim” because when I comment out “randomize_cube_positions” (lines 49~57) in the “stack_joint_pos_env_cfg.py” script, the cubes are rendered correctly. The “write_root_pose_to_sim” is used in the “randomize_object_pose” function which is defined in the “franka_stack_events.py” scritp.
Can you please look into it?

**Comment by WenjingLi2036** [comment]
> Hi [@WenjingLi2036](https://github.com/WenjingLi2036) , This is fixed in Isaac Sim 5.1.0, can you update your Isaac Sim and try again?

The issue is fixed for me. I updated to IsaacSim 5.1 and used the latest IsaacLab. Thanks for your support!
